algoritmo "estoque do mercadinho do pará"
// Função :ver se esta faltando produtos no mercadinho do pará
// Autor :Gabriel Martins
// Data : 14/04/2026
// Seção de Declarações
var
idade:real
javaScript:literal
python:literal
usuario:caractere
inicio
// Seção de Comandos
escreva("usuario:")
leia(usuario)
se (usuario="candidato")entao
escreval ("login correto")






-----------------------------------

escreva("idade do candidato:")
leia (idade)
se(idade>=18)ou (idade<18)entao
escreval("idade aceita")senao("idade nao aceita")

se (python="s")ou (python="n")entao
escreval("corriculo aceito") senao ("curriculo não aceito")

se (javaScript="s")ou (javaScript="n")entao
escreval("curriculo aceito") senao ("curriculo não aceito")

fimse
fimse
fimse
fimalgoritmo


