algoritmo "vai ser reprovado ou não?"

// Autor : Nicolas Ribeiro
// Aperte F9 para funcionar
// Data : 14/04/2026

var

nota : real
fre : literal


inicio

   escreva ("informe sua nota:")
   leia (nota)

   escreva ("informe a sua frequência:")
   leia (fre)

   se (nota>= 7) e (fre>= "75") entao
   escreval ("o aluno foi aprovado")

   senao
   escreval ("o aluno foi reprovado")
   fimse



fimalgoritmo
fimse
fimalgoritmo
